name: CI

on: pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Run CI
        uses: ./.github/workflows/base-ci.yml
        with:
          python-version: ${{ matrix.python-version }}
